export const commonPasswords: string[] = [
  "password",
  "123456",
  "qwerty",
  "admin",
  "letmein",
  "welcome",
  "monkey",
  "sunshine",
  "password1",
  "123456789",
  "football",
  "iloveyou",
  "1234567",
  "123123",
  "12345678",
  "abc123",
  "qwerty123",
  "1q2w3e4r",
  "baseball",
  "password123",
  "superman",
  "987654321",
  "mypass",
  "trustno1",
  "hello123",
  "dragon",
  "1234",
  "555555",
  "loveme",
  "hello",
  "hockey",
  "letmein123",
  "welcome123",
  "mustang",
  "shadow",
  "12345",
  "passw0rd",
  "abcdef",
  "123abc",
  "football123",
  "master",
  "jordan23",
  "access",
  "flower",
  "qwertyuiop",
  "admin123",
  "iloveyou123",
  "welcome1",
  "monkey123",
  "sunshine1",
  "password12",
  "1234567890",
];

export enum ErroresValidacion {
  NO_MAYUS_MINUS = "La clave debe de tener mayúsculas y minúsculas",
  NO_NUMBERS = "La clave debe de tener números",
  NO_SPECIAL_CHAR = "La clave debe de tener caracteres especiales",
  MIN_LENGTH = "La clave debe de tener una longitud mínima de 8 caracteres",
  USER_NAME = "La clave no debe tener el nombre del usuario",
  COMMON_PASS = "La clave no debe de contener palabras comunes",
}
